Repository ngxs/store, pull requests merged in 2018-04, with the labels that each got.

#142 Add Angular 6.0.0 and rxjs 6.0.0 support
  integration/app/app.component.ts
  integration/app/list/list.component.ts
  package-lock.json
  package.json
  packages/store/src/actions-stream.ts
  packages/store/src/of-action.ts
  packages/store/src/state-factory.ts
  packages/store/src/state-stream.ts
  packages/store/src/store.ts
  packages/store/src/symbols.ts
  packages/store/tests/dispatch.spec.ts
  packages/store/tests/select.spec.ts
  packages/store/tests/store.spec.ts
  tslint.json
  yarn.lock
Labels: domain:core, priority:2, type:chore

#164 added form-plugin and docs. modified integration app. to test form-plugin
  docs/plugins/form.md
  integration/app/app.component.ts
  integration/app/app.module.ts
  integration/app/todo.state.ts
  package.json
  packages/form-plugin/README.md
  packages/form-plugin/index.ts
  packages/form-plugin/ng-package.json
  packages/form-plugin/package.json
  packages/form-plugin/src/actions.ts
  packages/form-plugin/src/directive.ts
  packages/form-plugin/src/form.module.ts
  packages/form-plugin/src/form.plugin.ts
Labels: domain:plugins, type:feature

#203 feat: cancellable actions
  packages/store/src/action.ts
  packages/store/src/of-action.ts
  packages/store/src/state-factory.ts
  packages/store/src/store.ts
  packages/store/src/symbols.ts
  packages/store/tests/dispatch.spec.ts
Labels: domain:core, priority:1, type:feature

#244 fix: action stream exposition
  CHANGELOG.md
  packages/store/src/actions-stream.ts
  packages/store/src/module.ts
  packages/store/src/store.ts
Labels: domain:core, priority:1, type:chore

#285 Feature Router Plugin
  package.json
  packages/router-plugin/README.md
  packages/router-plugin/index.ts
  packages/router-plugin/ng-package.json
  packages/router-plugin/package.json
  packages/router-plugin/src/router.actions.ts
  packages/router-plugin/src/router.module.ts
  packages/router-plugin/src/router.state.ts
  packages/router-plugin/src/serializer.ts
  packages/router-plugin/src/symbols.ts
  packages/router-plugin/tests/router.plugin.spec.ts
Labels: domain:plugins, need feedback, type:feature

#306 chore: update ng-packagr and rxjs
  integration/app/app.component.ts
  integration/app/list/list.component.ts
  integration/app/todo.state.ts
  package-lock.json
  package.json
  packages/router-plugin/src/router.state.ts
  yarn.lock
Labels: domain:core, type:chore

#332 chore: upgrade rxjs to official
  package-lock.json
  package.json
  packages/devtools-plugin/package.json
  packages/form-plugin/package.json
  packages/logger-plugin/package.json
  packages/router-plugin/package.json
  packages/storage-plugin/package.json
  packages/store/package.json
  packages/websocket-plugin/package.json
  packages/websocket-plugin/src/websocket-subject.ts
  yarn.lock
Labels: domain:core, domain:plugins, priority:1, type:chore
