Repository ngxs/store, pull requests merged in 2019-05, with the labels that each got.

#1048 fix(hmr-plugin): correct persistence state in runtime
  integration/app/counter/counter.state.ts
  package.json
  packages/hmr-plugin/src/hmr-bootstrap.ts
  packages/hmr-plugin/src/hmr-manager.ts
  packages/hmr-plugin/src/internal/hmr-lifecycle.ts
  packages/hmr-plugin/src/internal/hmr-storage.ts
  packages/hmr-plugin/src/public_api.ts
  packages/hmr-plugin/src/symbols.ts
  packages/hmr-plugin/src/tests/hmr-helpers.ts
  packages/hmr-plugin/src/tests/hmr-mock.ts
  packages/store/internals/src/index.ts
  packages/store/internals/src/initial-state.ts
  packages/store/internals/src/object-utils.ts
  packages/store/internals/src/symbols.ts
  packages/store/internals/testing/src/ngxs.setup.ts
  packages/store/internals/testing/src/symbol.ts
  packages/store/internals/testing/tests/ngxs.setup.spec.ts
  packages/store/src/actions/actions.ts
  packages/store/src/configs/messages.config.ts
  packages/store/src/internal/internals.ts
  packages/store/src/internal/state-factory.ts
  packages/store/src/internal/state-stream.ts
  packages/store/src/module.ts
  packages/store/src/store.ts
  packages/store/src/symbols.ts
  packages/store/tests/default-states.spec.ts
Labels: BUGFIX

#1061 fix(form-plugin): introduce conditional debounce
  docs/plugins/form.md
  packages/form-plugin/src/directive.ts
  packages/form-plugin/tests/form.plugin.spec.ts
Labels: BUGFIX

#1059 feat(router-plugin): add `RouterDataResolved` action
  packages/router-plugin/src/router.actions.ts
  packages/router-plugin/src/router.state.ts
  packages/router-plugin/tests/router.plugin.spec.ts
Labels: FEATURE, domain:plugins

#1066 perf(store): replace `spread` with `slice` in the operator functions
  packages/store/operators/src/insert-item.ts
  packages/store/operators/src/remove-item.ts
  packages/store/operators/src/update-item.ts
Labels: domain:core, ready to release

#1091 fix(socket-plugin): don't stop WebSocketSubject stream after dispatching WebSocketDisconnected
  packages/websocket-plugin/src/public_api.ts
  packages/websocket-plugin/src/symbols.ts
  packages/websocket-plugin/src/websocket-handler.ts
  packages/websocket-plugin/src/websocket-subject.ts
  packages/websocket-plugin/tests/websocket.module.spec.ts
Labels: BUGFIX, domain:plugins
