Repository ngxs/store, pull requests merged in 2019-11, with the labels that each got.

#1400 chore: add ngxs 3.6 announcement article
  publication/2019-10-21_announcing_ngxs_3_6/article.md
Labels: on hold

#1436 feat(store): implements StateToken<T>
  docs/SUMMARY.md
  docs/advanced/token.md
  docs/concepts/state.md
  integration/app/store/todos/todos.state.ts
  integrations/hello-world-ng5/package.json
  packages/storage-plugin/src/internals.ts
  packages/store/src/decorators/select/select.ts
  packages/store/src/decorators/select/symbols.ts
  packages/store/src/decorators/selector/selector.ts
  packages/store/src/decorators/selector/symbols.ts
  packages/store/src/decorators/state.ts
  packages/store/src/public_api.ts
  packages/store/src/state-token/state-token.ts
  packages/store/src/state-token/symbols.ts
  packages/store/src/store.ts
  packages/store/src/symbols.ts
  packages/store/src/utils/store-validators.ts
  packages/store/tests/dev-mode.spec.ts
  packages/store/tests/module.spec.ts
  packages/store/tests/select.spec.ts
  packages/store/tests/selector.spec.ts
  packages/store/tests/state-token.spec.ts
  packages/store/types/tests/selection.lint.ts
  packages/store/types/tests/state-token.lint.ts
Labels: domain: core, on hold

#1453 feat(store): improved typings for @Select decorator
  docs/advanced/token.md
  packages/store/src/decorators/select/symbols.ts
  packages/store/types/tests/selection.lint.ts
  packages/store/types/tests/state-token.lint.ts
Labels: domain: core
